export const data = {
    phrases: [
    "Holi amor, mi niña, ¿Como estás? y si, este es el proyecto en el que tanto trabajaba, desde ese dia de amor y amistad, solo se intencificaron más mis ganas de hacer algo de este tipo para ti, además me dijiste que te gusaría algo asi jijiaji. Me gustaría decirte lo mucho mucho que te amo. Esto iba destinado para la fecha que te dije, pero ya estamos muy lejos, entonces, será un regalo normalito, peerooo, con mucho mucho amor, mi niña preciosa, mi cielito lindo, mi estrellita.",

    'Me sigue pareciendo increible la forma en que nos conocimos, quien diría que de mi lugar de practicas lleagaría el amor de mi vida. Cuando ya todo me parecia un poco gris, cuando ya queria irme, simplemente llegaste tú, y para quedarte por siempre, porque debemos estár juntos por siempre mi amor. Que equivocado estaba cuando pensaba que solo serías una random más en mi vida, disfrazada de una niña tierna y pequeña y al final terminaste siendo lo que más aprecio, lo que mas amo, lo que llevo my dentro, una persona extremadamene especial para mi, a la cual me siento demsiado impulsado por protejer, amar, cuidar, valorar, consentir, HACERLA FELIZ, me encanta, literalmete me encanta haberme cruzado contigo, te amo, te amo demasiado, estamos destinados a ser felices juntos, mi Allison, te amo <3.',
    
    "SOY una persona muy afortunada, ¿Sabes por que? Porque te tengo a ti, tengo a la mujer más bonita del universo, la mas bella, la más hermosa. Sabes que siempre me pareciste muy bonita, muy, linda, tierna, adorable muy tú. Te juro que eres lo más precioso e increible que puedo tener a mi vista, siempre lo fuiste, siempre lo serás. Todo, todo de ti, Allison, absolutamente cada detalle de ti me encanta, me enamoré de ti, muchisimo, y no solo por lo fisico, sino tambien por tu interior, eres bellisima por dentro y por fuera, me encanta tu forma de pensar, com reflexionas, como te expresas, todo todo de ti me gusta. Estoy totalmente seguro de que estoy con la mejor persona de todos los tiempos. Allison, mi vida, eres mi humana favorita, te amo <3.",

    "Amor, desde el punto que nos conocemos hasta ahora, te juro que ha sido el mejor lapso de tiempo de mi vida, una etapa en la que el sentir es muy fuerte, el pensamiento muy cargado, donde te conocí, no hubo mejor combinación. Cada momento que he pasado contigo, haciendo, diciendo, viendo, escuchando, pensando, en cualquier cosa, han sido muy increibles. Haz hecho que mi vida cambie radicalmente, marcado un antes y un despues, no puedo ni imaginar que sería de mi en este momento si no estuviera contigo, y no quiero vivir en un mundo de ilusiones lejano porque quiero estar en esta linea temporal, en la cual estoy contigo, estar contigo es demasiado lindo, es lo que más quiero. Me has hecho pensar de manera seria en mi como persona, pensar en los demás, en visiones a futuro solidas, en que quiero ser y por que. Quiero ser una mejor persona para mi, para ti y para cualquiera que me rodee, siendo muy muy EXTREMADAMETE FELÍZ.",

    "Amor, de verdad de verdad te digo que soy muy feliz contigo, eres todo lo que necesito en realidad, y sabes que no estoy exagerando JIJAISJIAJ. Me encanta estár contigo, eres mi mejor amiga, la persona mas cercana ue tengo, mi camiga fiel, la persona con la que puedo expresarme de verdad, sinceramente, la persona que me apoya, que me aconseja, que me implulsa a mejorar cada vez más, la que me ama mucho, me quiere y que está dispuesta a estár conmigo para toda la vida, tal como yo, y eso me encanta. Me gusta muchisimo hablar contigo, contare cualquier cosa, que tú me digas cualquier cosa, intrcambiar pensamientos, entrañarnos y comprendernos cada vez más para poder acoplarnos mucho mejor, decirnos cosas bonitas hasta el punto de querer llorar de sentiiento, acercarnos cada vez más mi vida. Te amo, TE AMO COMO NO TIENES IDEA, me fascinas, nunca quiero que te separes de mi lado porque sabes perfectamente lo importante que eres para mi y quiero pasar contigo toda mi vida, toda mi existencia tanto en la vida como la muerte, o en donde sea mi amorcito jiji.",

    "Amor, tú literalmente has sido lo máximo para mi, me has hecho muy feliz y has estado siempre ahí para mi, y eso me encanta, pero sabes que yo tambien quiero y deseo muchisimo que TÚ TAMBIEN ESTÉS FELIZ, amor, que te sientas comoda, en paz, en confianza, que te sientas escuchada, comprendida, que realmente sientas que tienes a alguien de tu lado, alguien que te comprende y siempre siempre va a apoyarte en cualquier cosa que te propongas, que nunca absolutamente nunca te sientas sola, sino felz. Yo quiero ser esa persona amor, yo soy el que quiere estar contigo para siempre, por toda la vida contigo, el que más te ame, el que lucha por ti. Yo siempre te tendré en cuenta, te tendré fé, confianza, te escucharé y alentaré en cualquier ocación, quiero que me veas lo mas cercano posible, como si ya hubieses pasado una verdadera eternidad conmigo. Quiero ser tu mejor amigo, tu confidente, tu perro, tu persona favorita mi amor, tu noviooooo, quiero serlo todo para ti, mi vida. TE AMOOOOOO <3.",

    "Amor, me gusta todo de ti, me gusta hacer de todo contigo, cada segundo que paso contigo es increible ya sea contigo al lado mio o a travez de una pantalla, porque sabemos aprovecharlo, de una u otra forma haciendo coas que nos mantienen cómodos y nos entretienen. Me gusta cuando hablamos, me gusta cuando nos escuchamos, me gusta cuando reflexionamos, me gusta cuando pensamos, me gusta cuando nos cuidamos, me gusta cuando nos peleamos por ver quien ama más al otro, aunque es obvio que yo amor, aceptalo porfi, me gusta cuando mejoramos, me gusta cuando llenamos nuestrso vacíos, me  gusta cuando nos abrimos, me gusta cuando nos vemos, me gusta cuando hacemos videollamadas, me gusta cuando nos contamos nuestro dia, me gusta como nos amamos, me gusta todo de nosotros, ademas, me gusta todo especificamente de ti, me gusta cuando hablas, me gusta cuando me miras, me gusta cuando me dices bebé, me gusta cuando me dices que me amas, me gusta como te ves; con maquillaje o sin maquillaje; con o sin peinados, con o sin ropa, me gusta tu cuerpo, me gusta como me miras, me gusta muchisimo como me besas, me gusta tu forma de ser, me gusta tu forma de ver una relación, me gusta muchismo lo linda y tierna que eres, me gusta cuando me apoyas y me das aliento, amor es que me gusta todo de ti, de nosotros porque te amo demasiado, ocupas un lugar demasiao especial e importante en mi vida y la verdad no pienso apartarte de ahi JIJIASJIS. TE AMOOOOOOOOO Y ME ENCANTAS EN TODO SENTIDO.",

    "Amorcito, perdón si ya sueno repetitivo o redundante, pero es que simplemente no puedo dejar de escribir, aunque no sé bien como organizar esto que escribo, por eso es mucho JAJSJASJ, perdón por el mucho textooo. Entonces queria recalcarte algo muy obvio en ti y lo cual es lo único en que me ganas amor, queria decirte que ERES HERMOSAAAAAAAAA, ERES BELLISIMA, LINDA, PRECIOSA, ENCANTADORA, eres la mejor obra de arte que Dios pudo haber creado mi vida, me gustas muchisimo, me gustas demasiado, me ENCANTASSSS, y es que no puedo evitar decirlo, me derrito con solooo verte, me pongo nervioso, se me olvida que decir e incluso como hablar, y aunque eso me pase, verte y apreciarte ademas de saber que eres mia, es la mejor sensación de todo el universo, sabes tú muy bien lo mucho que me gusta verte, lo mucho que me encanta verte, tus fotitos, tus fotitos hermosasss, me encantan, ojala me mandaras fotos cada instante de tu vida, otro pov ademas del mio.", 

    "Amor, ¿Imaginas poder fusionar nuestros sentimientos, nuestra felicidad y por toda la vida? Yo sí, pero no, porque ha de ser algo magnifico, increible y único, pero sin duda muuuy lindo. Amorcito, realmente quiero que tú y yo tengamos un futuro juntos, que sigamos siempre conociendonos y evolucionando a partir de nuestro interior y lo que sentimos para asi poder mejorar para el otro y para uno mismo y cosechar de un hermoso amor puro y transparente. Amor yo quiero lo mejor para los 2, quiero que siempre estemos para el otro, vivir experencias, renovarnos, cada vez amarnos más, querernos más, viajar, comer, casarnos, terner nuestros hijos, auque sean gatos o loros o figuritas de tik tok, lo que sea, pero contigo y muy bonito, porque eso es lo que quiero, ser feliz contigo, toda la vida, en cualquier momento, en cualquier lugar, bajo cualquier circunsancia, como sea amor, pero muy felices. Quiro que estemos juntos en cada logro, cada meta, cada experiencia, felicitarnos, cada tropiezo cada bajón, buscar nuestras soluciones y continuar para poder disfrutar plenamente nuestra vida juntos.",

    "Amor, tambien quiero pedirte perdón, perdón por en ocasiones hacerte sobrepensar, perdón si te he hecho sentir insegura, perdón si te he hecho enojar, perdón si te hecho llorar :(, por aciones y desiciones que tomé sin saber como realmente te afectarían sin darme cuenta, perdón si me has sentido distante, perdón si crees que no me importas. Amorcito, yo se que hemos tenido nuestras diferencias varias veces, pero no quiero que niguna circunstancia o diferencia afecte nuestra relación, abslutamente nada. Me encanta como hemos llegado a acuerdos para poder hablarnos sobre estas cosas cuando suceden, porque ambos sabemos que nestra base más importante es la comunicación y por medio de ella podemos solucionar las diferencias y problemas que se nos enfrenten,asi como hemos echo a lo largo de nuestra historia. Me encanta que ambos buscamos siempre una solución, no queremos dañarnos, no queremos dejar la relación, que por el contrario buscamos estar bien, buscar querernos más y ser más fuertes para ambos. Me encanta que siempre llegamos a un pacto, una solución saludable para ambos, porque eso solo demuestra el verdadero amor que sentimos, esas ganas de salir adelante y ser más felices. Me encanta esa sensación de felicidad y amor renovados despues de estos episodios, solo me hace amarte más, quererte más estár más a tu cuidado mi amor. Por favor perdoname y no peleemos jasjs y si alguna vez pasa, hallemos una solución y salgamos adelante juntos.",

    "Amorcito, mi amor por ti es inefable, pero intenataré explicartelo. Yo, Luis, a ti, Allison, mi vida, te amo demasiado, te amo inmenso, mi amor por ti es grandisimo y a su vez incomprendido por ti. Cuando te veo, aunque tú dices que no se me nota, me paralizo, me emocino me da muchisimo gusto, me dan nervioosss, me encanta volver a verte, recalacarme que eres el amor de mi vida y que eres lo mejor que me ha pasado. Mi amor por ti es an grande, pesado y fuerte como la masa del universo entero elevada a infinito, mas allá de cualquier barera física o mental, de cualquier dimensión, de cualquier adverwsidad y me sorprende como puede caber todo eso en mi pecho, como aún no me has hecho explotar, como puedo llegar a amrte tanto mi amor. Mi amo por ti es tan lindo y real como ver un amanecer o un anochecer, como beber un chocolate o como comer pizza, perro o pizaperro JJASJJJASJ, como ver tu hermosa carita, todo este amor es para ti, para nadie más, nadie lo merece tanto como tú y no se lo daré a absolutamente nadie que no seas tú, porque tú eres la que lo provoca, tú eres la que le da sentido, quiero amarte por siempre, por toda la eternidad de una manera muy sincera y bonita y verdadera. Y amor, por si no te has dado cuenta o por si no te ha quedado claro, YO LUIS MIGUEL BARIOSNUEVO PACHECO TE AMO MUCHISISISISIMO MÁS A TI, ALLISON SIFÍA RUÍZ PÁEZ, yo te amo mucho más a ti mi amor, te amo <3.",

    "Amorcito de verdad que te amo y eres súper importante y especiál para mi eres todooo, eres mi niña hermosa, mi amor, mi novia, mi mejor mi amiga, mi confidente, mi soprte, mi pastelito, mi chocolate,  mi mañana, mi noche, mi luz, mi cielo, mi aire, mi tierra, mi vida, mi chiquita bella, mi bebé, mi preciosa, mi linda, mi mundo, mi confianza, mi paz, mi norte, mi guia, mi amanecer, mi anochecer, mi dulce niña, mi realidad, mi única, mi inigualable, mi esplendida, mi inteligente, mi divertida, mi increible, mi deseable, mi amada, mi diosa, mi espiritu, mi alma, mi vista, mi sentido, mi enfoque, mi amor platónico, mi lucura, mi debilidad, mis ganas, mi motivación, mis pensamientos, mi mente, mi pieza faltante, mi complemento, mi sangre mi corazón, mis fuerzas, mi comida, mi agua, mis energías, mi reposo, mi descanzo, mi amiga fiel, mi hermosa bela preciosa NOVIAAA, MII ALLISONNN, mi amor tú lo eres todo para mí, absolutamente todo mi amor, eres lo que más amo, lo que mas deseo, con la qu quiero pasar mi vida.<br><span style='color:red; font-weigh: bolder; font-size: 30px;'>Allison, eres mi todo, mi absoluto todo</span>",

    "Mi amor, mi Allison, mi vida, quize tocar varios puntos, varios aspectos de nosotros y creo que lo hice con la mayoría, si crees que falta algo avisame, quiero que esto sea una reliquia para ambos y tenga todo lo fundamental para nosotros. Por favor toma este regalo como una muestra de mi inmenso amor por ti, creeme que lo hice con mucho cariño, aunque no lo he terminado JAJSJAJSA, tal vez esta conclusión la modifique cuando ya esté toda terminada, pero mientras te hablo a ti por medio de esta.", 

    "Realmente estoy absolutamente agradecido con todo lo que trajiste a mi vida mi amor, toda la felicidad, todos los buenos momentos, todas las lindas cosas que nos compartimos, todo el amor que sentimos. Relamente soy muy feliz contigo y quiero seguir asi paraa siempre mi vida, te amo, te amo un montón, y quiero que tú tambien seas feliz conmigo, ser tu hombre y que seas mi mujer. No quiero que por nada del mundo nos separemos, te juro que lo que más quiero ahora mismo es estár lo mas cerca de ti posible, verte, abrazarte fuerte, darte un besito y decirte ue te amo. Allison quiero que avancemos juntos, siempre tú y yo y que nuestro amor esté de por medio, quiero ser muy feliz contigo, quiero que seamos los más felices del mundo a nuestra manera. Te amo mi amor, no sé que decir, pero es que te amo, te amo un montón, vives en mi mente y corazón y jamás pienso dejar que te vayas de TU hogar, eres el segundo regalo que Diós me dió despues de esta vida en la que estoy contigo, te amo, te amo mucho mi amor. TE AMO.",

    "<span style='color:green; font-weigh: bolder; font-size: 30px;'>Allison, amor, yo sé que me amas, simepre lo supe, pero...</span> <br> <span style='color:orange; font-weigh: bolder; font-size: 30px;'>Allison, mi vida, ¿Sabías que yo te amo?</span> <br> Porque si, asi es, te amo un montón <br><br> TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMO TE AMOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"

    ],
    images: [
    "../../For-All/resources/imagesDedi/f1.webp", 
    "../../For-All/resources/imagesDedi/f2.jpeg", 
    "../../For-All/resources/imagesDedi/f3.jpeg",
    "../../For-All/resources/imagesDedi/f4.jpeg",
    "../../For-All/resources/imagesDedi/f5.jpeg",
    "../../For-All/resources/imagesDedi/f6.jpeg",
    "../../For-All/resources/imagesDedi/f7.jpeg",
    "../../For-All/resources/imagesDedi/f8.jpeg",
    "../../For-All/resources/imagesDedi/f9.jpeg",
    "../../For-All/resources/imagesDedi/f10.jpeg",
    "../../For-All/resources/imagesDedi/f11.jpg",
    "../../For-All/resources/imagesDedi/f12.jpg",
    "../../For-All/resources/imagesDedi/yo.jpeg",
    "../../For-All/resources/imagesDedi/f13.jpg",
    "../../For-All/resources/imagesDedi/f14.jpeg"
    ]
}